### ISSUE TITLE
'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Deliki** [djc/abna#5]
what can we do about this?

Traceback (most recent call last):
  File "H:\DelloTrade\B. DelloTrade Dev\DelloCode\AbnAmro.py", line 4, in <module>
    sess.login(, '')
  File "C:\Users\dsama\Python\DelloEnv\lib\site-packages\abna\__init__.py", line 33, in login
    response = calculate_response(challenge['challenge'], challenge['userId'], token)
  File "C:\Users\dsama\Python\DelloEnv\lib\site-packages\abna\__init__.py", line 60, in calculate_response
    obj = decode(challenge)
  File "C:\Users\dsama\Python\DelloEnv\lib\site-packages\abna\__init__.py", line 81, in decode
    bytes = hex2ba(challenge)
  File "C:\Users\dsama\Python\DelloEnv\lib\site-packages\abna\__init__.py", line 110, in hex2ba
    return [i for i in s.encode('ascii').fromhex(s)]
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by djc** [comment]
So apparently you're getting a `null` `challenge` from `/session/loginchallenge`? Not sure what's up with that. I'm not seeing it -- the failure mode I've seen is intermittent and manifests as a `JSONDecodeError`.

**Comment by Deliki** [comment]
Bedoel je dat het bij jou wel werkt?

Verstuurd vanaf mijn iPhone

Op 27 sep. 2022 om 22:14 heeft Dirkjan Ochtman ***@***.***> het volgende geschreven:

﻿

So apparently you're getting a null challenge from /session/loginchallenge? Not sure what's up with that. I'm not seeing it -- the failure mode I've seen is intermittent and manifests as a JSONDecodeError.

**Comment by djc** [comment]
Yup, hier werkt het gewoon.

**Comment by Deliki** [comment]
Heb je bepaalde instellingen in abn amro die hiervoor geactiveerd moeten zijn. Want het werkte eerst ook bij mij.

Verstuurd vanaf mijn iPhone

Op 27 sep. 2022 om 22:32 heeft Dirkjan Ochtman ***@***.***> het volgende geschreven:

﻿

Yup, hier werkt het gewoon.

**Comment by djc** [comment]
Voor zover ik weet niet.

**Comment by Deliki** [comment]
[SOLVED] My code was blocked, I needed to reinstall the app on my phone and login and register my account.
